### DISCUSSION TITLE
Can't upload image when I -v the /upload folder.

### DISCUSSION THREAD

**Discussion by mikexfreeze** [LycheeOrg/Lychee#2408] [Q&A]
I already give Lychee the root authority by set the puid/guid=0
![image](https://github.com/LycheeOrg/Lychee/assets/16068816/7b58a7d8-427b-4011-8340-37a0508a0b31)

 ```
Diagnostics
    -----------
        Warning: /v**********************lic/uploads/ has permissions 0777, but should have 2775
        Warning: /v**********************lic/uploads/import has permissions 0777, but should have 2775
        Warning: /v**********************lic/uploads/livewire-tmp has permissions 0777, but should have 2775
        Warning: /v**********************lic/uploads/medium has permissions 0777, but should have 2775
        Warning: /v**********************lic/uploads/medium2x has permissions 0777, but should have 2775
        Warning: 7 more directories with wrong permissions
        Warning: Dropbox import not working. dropbox_key is empty.
        Info: Latest version of PHP is 8.3
        Warning: git (software) is not available.
    
    System Information
    ------------------
        Lychee Version (tag):                    v5.2.2 (6a0bebe) -- Up to date (0 seconds ago).
        DB Version:                              5.2.2
        
        composer install:                        --no-dev
        APP_ENV:                                 production
        APP_DEBUG:                               false
        APP_URL:                                 set
        APP_DIR:                                 default
        LOG_VIEWER_ENABLED:                      true
        LIVEWIRE_ENABLED:                        true
        
        System:                                  Linux
        PHP Version:                             8.2.18
        PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
        Timezone:                                Asia/Shanghai
        Max uploaded file size:                  100M
        Max post size:                           100M
        Livewire chunk size:                     12.00 MB
        Max execution time:                      3600
        SQLite Version:                          3.40.1
        
        exec() Available:                        yes
        Imagick Available:                       1
        Imagick Enabled:                         1
        Imagick Version:                         1691
        GD Version:                              2.3.3
        Number of foreign key:                   10 found.
    
    Config Information
    ------------------
        version:                                 050202
        check_for_updates:                       0
        sorting_photos_col:                      taken_at
        sorting_photos_order:                    ASC
        sorting_albums_col:                      max_taken_at
        sorting_albums_order:                    ASC
        imagick:                                 1
        skip_duplicates:                         0
        small_max_width:                         0
        small_max_height:                        360
        medium_max_width:                        1920
        medium_max_height:                       1080
        lang:                                    en
        image_overlay_type:                      desc
        default_license:                         none
        compression_quality:                     90
        grants_full_photo_access:                1
        delete_imported:                         0
        mod_frame_enabled:                       1
        mod_frame_refresh:                       30
        thumb_2x:                                1
        small_2x:                                1
        medium_2x:                               1
        landing_page_enable:                     0
        force_migration_in_production:           0
        search_public:                           0
        hide_version_number:                     0
        SL_enable:                               0
        SL_for_admin:                            0
        recent_age:                              1
        grants_download:                         0
        photos_wraparound:                       1
        map_display:                             0
        zip64:                                   1
        map_display_public:                      0
        map_provider:                            Wikimedia
        force_32bit_ids:                         0
        map_include_subalbums:                   0
        update_check_every_days:                 3
        has_exiftool:                            1
        share_button_visible:                    0
        import_via_symlink:                      0
        has_ffmpeg:                              1
        location_decoding:                       0
        location_decoding_timeout:               30
        location_show:                           1
        location_show_public:                    0
        rss_enable:                              0
        rss_recent_days:                         7
        rss_max_items:                           100
        prefer_available_xmp_metadata:           0
        editor_enabled:                          1
        lossless_optimization:                   0
        swipe_tolerance_x:                       150
        swipe_tolerance_y:                       250
        local_takestamp_video_formats:           .avi|.mov
        log_max_num_line:                        1000
        unlock_password_photos_with_url_param:   0
        nsfw_visible:                            1
        nsfw_blur:                               0
        nsfw_warning:                            0
        nsfw_warning_admin:                      0
        nsfw_banner_override:                    
        map_display_direction:                   1
        album_subtitle_type:                     oldstyle
        upload_processing_limit:                 4
        new_photos_notification:                 0
        legacy_id_redirection:                   1
        zip_deflate_level:                       6
        SA_enabled:                              1
        default_album_protection:                1
        album_decoration:                        layers
        album_decoration_orientation:            row
        allow_username_change:                   1
        auto_fix_orientation:                    1
        use_job_queues:                          0
        random_album_id:                         starred
        use_last_modified_date_when_no_exif_date: 0
        layout:                                  justified
        date_format_photo_thumb:                 M j, Y, g:i:s A e
        date_format_photo_overlay:               M j, Y, g:i:s A e
        date_format_sidebar_uploaded:            M j, Y, g:i:s A e
        date_format_sidebar_taken_at:            M j, Y, g:i:s A e
        date_format_hero_min_max:                F Y
        date_format_hero_created_at:             M j, Y, g:i:s A T
        date_format_album_thumb:                 M Y
        upload_chunk_size:                       0
        nsfw_banner_blur_backdrop:               0
        search_pagination_limit:                 1000
        search_minimum_length_required:          4
        photo_layout_justified_row_height:       320
        photo_layout_masonry_column_width:       300
        photo_layout_grid_column_width:          250
        photo_layout_square_column_width:        200
        photo_layout_gap:                        12
        display_thumb_album_overlay:             always
        display_thumb_photo_overlay:             hover
        default_album_thumb_aspect_ratio:        1/1
        use_album_compact_header:                0
        login_button_position:                   left
        back_button_enabled:                     0
        back_button_text:                        Return to Home
        current_job_processing_visible:          1
    
```
Error Log:
```
Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}:50 stream_copy_to_stream(): Read of 8192 bytes failed with errno=21 Is a directory
App\Image\Files\NativeLocalFile::append:119 stream_copy_to_stream(): Read of 8192 bytes failed with errno=21 Is a directory; caused by
App\Image\Files\NativeLocalFile::append:129 stream_copy_to_stream(): Read of 8192 bytes failed with errno=21 Is a directory; caused by
```
![image](https://github.com/LycheeOrg/Lychee/assets/16068816/7bea3feb-5739-436e-bc0e-7f7f394e62cf)

Thanks

**Comment by ildyria** [comment]
I suspect that the `stream_copy_to_stream()` is trying to copy with an empty filename for obscure reason.
Which leads to trying to write on a folder.

**Reply by ildyria** [reply]
@mikexfreeze can you tell me a bit more of your install ? Looks like docker something.

**Reply by mikexfreeze** [reply]
I start Lychee with:
```
docker run -d \
--name=lychee \
-v /media/Doc/config/lychee/conf:/conf \
-v /media/Doc/Photos/test-photos:/uploads \
-v /media/Doc/config/lychee/sym:/sym \
-p 90:80 \
lycheeorg/lychee
```
And change some env with portainer recreate the container

```
docker -v
Docker version v18.09.2, build v18.09.2

cat /proc/version
Linux version 4.9.76 (hacklog@arch-8700k) (gcc version 7.3.1 20180425 [linaro-7.3-2018.05 revision d29120a424ecfbc167ef90065c0eeb7f91977701] (Linaro GCC 7.3-2018.05) ) #1 SMP PREEMPT Thu Apr 11 20:39:46 CST 2019

```
And this volumn is NTFS type is that a problem?
Let me know if you need any other information.

Thanks

[192.168.1.7.har.zip](https://github.com/LycheeOrg/Lychee/files/15136742/192.168.1.7.har.zip)
![image](https://github.com/LycheeOrg/Lychee/assets/16068816/6e6936ff-03db-4146-b812-a6c2d1f18011)

**Reply by ildyria** [reply]
> And this volumn is NTFS type is that a problem?

Are you running on windows or Linux ?

**Reply by ildyria** [reply]
I would also recommend using a docker compose https://github.com/LycheeOrg/Lychee-Docker/blob/master/docker-compose.yml

**Reply by mikexfreeze** [reply]
![192 168 1 7_9443_ (1)](https://github.com/LycheeOrg/Lychee/assets/16068816/15c84ccc-f24b-4305-95ac-4c90cbdc2380)

Use compose same error

**Reply by mikexfreeze** [reply]
#-------------------------------------------
#  Docker Compose
# @RobLandry
# Repo : https://github.com/LycheeOrg/Lychee-Docker
#-------------------------------------------

services:
  lychee_db:
    container_name: lychee_db
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=lychee
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=lychee
    expose: 
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - lychee
    restart: unless-stopped

  lychee:
    image: lycheeorg/lychee
    container_name: lychee
    ports:
      - 90:80
    volumes:
      - /media/Doc/config/lychee/conf:/conf
      - /media/Doc/Photos/test-photos:/uploads
      - /media/Doc/config/lychee/sym:/sym
      - /media/Doc/config/lychee/logs:/logs
    networks:
      - lychee
    environment:
      - PUID=0
      - PGID=0
      # PHP timezone e.g. PHP_TZ=America/New_York
      - PHP_TZ=Asia/Shanghai
      - TIMEZONE=Asia/Shanghai
      #- APP_NAME=Laravel
      #- APP_ENV=local
      #- APP_DEBUG=true
      #- APP_FORCE_HTTPS=false
      #- APP_URL=http://localhost
      #- APP_DIR=
      #- DEBUGBAR_ENABLEd=false
      #- LEGACY_V4_REDIRECT=false
      #- DB_OLD_LYCHEE_PREFIX=''
      - DB_CONNECTION=mysql
      - DB_HOST=lychee_db
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=lychee
      - DB_PASSWORD=lychee
      #- DB_PASSWORD_FILE=<filename>
      #- DB_LOG_SQL=false
      #- DB_LOG_SQL_EXPLAIN=false
      #- ENABLE_TOKEN_AUTH=true
      #- CACHE_DRIVER=file
      #- SESSION_DRIVER=file
      #- SESSION_LIFETIME=120
      #- QUEUE_CONNECTION=sync
      #- SECURITY_HEADER_HSTS_ENABLE=false
      #- SECURITY_HEADER_CSP_CONNECT_SRC=
      #- SECURITY_HEADER_SCRIPT_SRC_ALLOW=
      #- SESSION_SECURE_COOKIE=false
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_PASSWORD_FILE=<filename>
      #- MAIL_ENCRYPTION=null
      #- MAIL_FROM_NAME=
      #- MAIL_FROM_ADDRESS=
      #- TRUSTED_PROXIES=
      #- SKIP_PERMISSIONS_CHECKS
      - STARTUP_DELAY=30
      #- ADMIN_USER=admin
      #- ADMIN_PASSWORD=<ADMIN_PASSWORD>
      #- ADMIN_PASSWORD_FILE=<filename>
      ### Unused in Lychee
      #- REDIS_HOST=127.0.0.1
      #- REDIS_PASSWORD=null
      #- REDIS_PASSWORD_FILE=<filename>
      #- REDIS_PORT=6379
    restart: unless-stopped
    depends_on:
      - lychee_db

networks:
  lychee:

volumes:
  mysql:

**Reply by ildyria** [reply]
I'll try to get portainer running, but no guarantees. :(

**Reply by ildyria** [reply]
@mikexfreeze  Could you check this: https://mariushosting.com/how-to-install-lychee-on-your-synology-nas/
I am wondering if there are some info who could help you in there. [Marius](https://mariushosting.com/author/marius/) is pretty explicit on the PID etc.

**Reply by mikexfreeze** [reply]
I try to create new docker stack base on Marius compose file and instruction. Still same error 😅. I made some changes with his config because connection with DB and Redis didn't work correct. Here is the whole config:

```
version: "3.9"
services:
  db:
    container_name: lychee_db
    image: mariadb:10
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=lychee
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=lychee
    volumes:
      - /media/Doc/config/lychee/db:/var/lib/mysql:rw
    ports:
      - 3306:3306
    restart: always

  lychee:
    image: lycheeorg/lychee:latest
    container_name: Lychee
    hostname: lychee
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -f -s http://localhost:80/ || exit 1
    volumes:
      - /media/Doc/config/lychee/conf:/conf
      - /media/Doc/Photos/test-photos:/uploads
      - /media/Doc/config/lychee/sym:/sym
    environment:
      - PUID=0
      - PGID=0
      - PHP_TZ=Asia/Shanghai
      - TIMEZONE=Asia/Shanghai
      - DB_CONNECTION=mysql
      - DB_HOST=lychee_db
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=lychee
      - DB_PASSWORD=lychee
      # - CACHE_DRIVER=redis
      # - REDIS_HOST=lychee-redis
      # - REDIS_PASSWORD=null
      # - REDIS_PORT=6379
      - STARTUP_DELAY=10
      - APP_NAME=Laravel
      - APP_DEBUG=false      
      - APP_URL=http://192.168.1.7:90
      - TRUSTED_PROXIES=*
      - SECURITY_HEADER_HSTS_ENABLE=true
       #- MAIL_DRIVER=smtp
       #- MAIL_HOST=smtp.gmail.com
       #- MAIL_PORT=587
       #- MAIL_USERNAME=Your-own-gmail-address
       #- MAIL_PASSWORD=Your-own-gmail-address
       #- MAIL_ENCRYPTION=starttls
       #- MAIL_FROM_NAME=Your-own-gmail-address
       #- MAIL_FROM_ADDRESS=Your-own-app-password
    ports:
      - 90:80
    restart: always
    depends_on:
      db:
        condition: service_started
```
