### DISCUSSION TITLE
A facade root has not been set?

### DISCUSSION THREAD

**Discussion by remkolodder** [LycheeOrg/Lychee#2483] [Q&A] [answered]
Hello,

After updating to a more recent version recently, my (Docker) startup fails with:

PHP Fatal error:  Uncaught RuntimeException: A facade root has not been set. in /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:354
Stack trace:
#0 /var/www/html/Lychee/app/Exceptions/Handler.php(439): Illuminate\Support\Facades\Facade::__callStatic()
#1 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(617): App\Exceptions\Handler->report()
#2 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(198): Illuminate\Foundation\Console\Kernel->reportException()
#3 /var/www/html/Lychee/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#4 {main}
  thrown in /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 354

I must have missed something. Can someone share what I might have missed? or is this a bug instead?

**Comment by ildyria** [comment]
that is a weird one.
Can you clarify your setup, your version etc ?

**Comment by remkolodder** [comment]
hello,

Yes, I never had this before.

Version 5.5.0 (just updated to 5.5 as well, 5.3 and 5.4 also have it)

```
APP_NAME=Lychee
APP_ENV=production
APP_KEY=base64:KEYHERE
APP_DEBUG=true
APP_URL=internal_link

# enable or disable debug bar. By default it is disabled.
DEBUGBAR_ENABLED=false

##############################################################################
# IMPORTANT: To migrate from Lychee v3 you *MUST* use the same MySQL/MariaDB #
#            server as v3.                                                   #
##############################################################################

# Table prefix (e.g. lychee_) of a Lychee v3 instance for migration
DB_OLD_LYCHEE_PREFIX=

# DB_CONNECTION can be sqlite, mysql or pgsql. For sqlite the other entries are
# not required, but an existing sqlite3 database may be specified if desired. In
# this case, please use an absolute path. DB_DATABASE may be omitted but should
# *not* be left blank.
DB_CONNECTION=mysql
DB_HOST=lychee_db
DB_PORT=3306
DB_DATABASE=lychee
DB_USERNAME=lychee
DB_LOG_SQL=false

# List foreign keys in diagnostic page
DB_LIST_FOREIGN_KEYS=true

# Application timezone. If not specified, the server's default timezone is used.
# Requires a named timezone identifier.
# See https://www.php.net/manual/en/timezones.php for the list of supported timezones.
# Don't use a timezone offset (like +01:00) or a timezone abbreviation (like CEST)
# TIMEZONE=UTC

# Visibility of directories and (media) files in LYCHEE_UPLOADS
# Possible values are:
#
#  - private: world group has neither read nor write access
#  - public: world group has read access but no write access (the default)
#  - world: world group has read and write access
#
# The default should suffice for most installations.
# For improved security, change this setting to "private".
# Some rare setups may require directories and files to be world writeable.
# In this case, use "world" here.
# USE WITH PRECAUTIONS: world writeable files and folders may be a SECURITY RISK.
# LYCHEE_IMAGE_VISIBILITY=public

# folders in which the files will be stored
# LYCHEE_UPLOADS="/var/www/html/Lychee-Laravel/public/uploads/"

# url to access those files
# LYCHEE_UPLOADS_URL="uploads/"

CACHE_DRIVER=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=1200

SECURITY_HEADER_HSTS_ENABLE=false
SESSION_SECURE_COOKIE=false

REDIS_HOST=lychee_cache
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=
MAIL_FROM_NAME=
MAIL_FROM_ADDRESS=

# The trusted proxies if Lychee is behind a reverse proxy
# Accepted values:
#  - `null`: no proxy
#  - `*`: any proxy
#  - <ip address>[,<ip address>]: a comma-seperated list of IP addresses
TRUSTED_PROXIES=*

# Comma-separated list of class names of diagnostics checks that should be skipped.
#SKIP_DIAGNOSTICS_CHECKS=
TIMEZONE=UTC
```

Docker compose:

```
  lychee:
    image: lycheeorg/lychee:v5.5.0
    container_name: lychee
  #  ports:
  #    - 90:80
    volumes:
      - /docker/lychee/conf:/conf
      - /docker/lychee/uploads:/uploads
      - /docker/lychee/sym:/sym
      - /docker/lychee/php:/etc/php
      - /storage:/storage # (symlink to rw nfs share)
    networks:
      lychee:
      revproxy:
        ipv4_address: <internal ip>
    environment:
      #- PUID=1000
      #- PGID=1000
      # PHP timezone e.g. PHP_TZ=America/New_York
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      #- APP_NAME=Laravel
      #- APP_ENV=local
      #- APP_FORCE_HTTPS=false
      #- APP_DEBUG=true
      #- APP_URL=http://localhost
      #- LOG_CHANNEL=stack
      - DB_CONNECTION=mysql
      - DB_HOST=lychee_db
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=lychee
      - DB_PASSWORD=<redacted>
      #- DB_DROP_CLEAR_TABLES_ON_ROLLBACK=false
      #- DB_OLD_LYCHEE_PREFIX=''
      #- BROADCAST_DRIVER=log
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=1200
      #- QUEUE_DRIVER=sync
      #- SECURITY_HEADER_HSTS_ENABLE=false
      - REDIS_HOST=lychee_cache
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_ENCRYPTION=null
      #- PUSHER_APP_ID=''
      #- PUSHER_APP_KEY=''
      #- PUSHER_APP_SECRET=''
      #- PUSHER_APP_CLUSTER=mt1
      - STARTUP_DELAY=30
    restart: unless-stopped
    depends_on:
      - lychee_db
```
