### DISCUSSION TITLE
Authelia Config Not Working

### DISCUSSION THREAD

**Discussion by EricWvi** [LycheeOrg/Lychee#3312] [Bugs] [answered]
### Lychee version

Lychee 6.5.3

### Which PHP version are you using?

PHP 8.4

### Detailed description of the problem

I use docker version of lychee.
I config the Oauth in .env file.
I can not make Authelia show in the login modal. But Github, Facebook, keyclock work.
When I delete the config, the three icons are still there. Weird! When I changed the value of the ENV vars, the web icon changes too. But delete the config does not work.
I already tried to recreate the container many times.
<img width="201" alt="image" src="https://github.com/user-attachments/assets/09aaec37-3fe3-45ba-afcc-277443157c27" />
<img width="139" alt="image" src="https://github.com/user-attachments/assets/75dac3c1-12bc-4f11-91fb-c95d6c8168b1" />

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I understand my bug report will be removed if I haven't met the criteria above.

**Comment by ildyria** [comment]
Thank you for your report, I will have a look.
It would have helped us if you provided us with the diagnostic page too. Those information gives us details such as e.g. if you are running on docker, which docker image you use etc...

**Comment by EricWvi** [comment]
@ildyria 
I use `lycheeorg/lychee       latest    60b5227406c9   6 days ago`.
This problem just like a ghost, I do not have any idea why it would happen. 🤣

**Reply by EricWvi** [reply]
docker compose:
```
  lychee:
    image: lycheeorg/lychee
    container_name: lychee
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - xxxxxxx:/conf
      - xxxxxx:/uploads
      - xxxxxxx:/sym
    env_file:
      - /path/to/lychee.env
    environment:
      - PHP_TZ=Asia/Shanghai
      - APP_URL=https://xxxxxx/
      - APP_FORCE_HTTPS=true
      - TRUSTED_PROXIES=*
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=root
    networks:
      - my-network
```
