### ISSUE TITLE
Non-static method App\Assets\Helpers::cacheBusting() cannot be called statically - error after migration from 4.3

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee#1536]
Hi,

I'm using Lychee in a docker container with mariadb, I took docker compose yaml from linuxserver.io - https://docs.linuxserver.io/images/docker-lychee

It worked fine for over one year on my raspberry pi. Today, I wanted to migrate this app to different system, so I stopped it, both with database, migrated all config files (including database files) to new system, prepared new yaml file:

```
version: "3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb:latest
    container_name: lychee_mariadb
    restart: always
    volumes:
      - /mnt/drives/appdata/lychee/lychee_mariadb:/config
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=dbpassword
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Warsaw
  lychee:
    image: ghcr.io/linuxserver/lychee:latest
    container_name: lychee
    restart: always
    depends_on:
      - mariadb
    volumes:
      - /mnt/drives/appdata/lychee/lychee_config:/config
      - /mnt/drives/pictures/lychee_pics:/pictures
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=lychee
      - DB_PASSWORD=dbpassword
      - DB_DATABASE=lychee
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Warsaw
    ports:
      - 172.17.0.1:8081:80
      - 8082:80
```

port forwarding 8082:80 was set only for debugging purpose. Once I started it, I got 500 error in the browser, so I set APP_DEBUG to true in .env file and now web ui shows some symphony error, which I don't understand:

https://imgur.com/a/XeUGwZE

Is there any way to fix that?
