### ISSUE TITLE
Layout changed after upgrading to 4.6.2

### ISSUE THREAD

**Issue by sigulete** [LycheeOrg/Lychee#1613]
I don't use Smart Albums, so I followed the instructions from the documentation (FAQ) to remove that block. 
The CSS code I use in settings under **Personalized CSS** is as follows:

```
[data-id="unsorted"] { display:none; }
[data-id="public"] { display:none; }
[data-id="starred"] { display:none; }
[data-id="recent"] { display:none; }
div.content > div.divider:first-child { display:none; }
div.content > div.divider:nth-child(6) {
    margin-top: 10px;
    border-top: 0;
    box-shadow: none;
}

```
The output in version 4.6.1 was as expected, the section related to Smart Albums was hidden.
However, the result after upgrading to 4.6.2 is as below.

**screenshot-user**

![screenshot-user](https://user-images.githubusercontent.com/35115643/204997452-5ffcaf4b-d0ea-425e-89a5-b82be8e58ae4.png)

This is the screenshot for a non-admin user. 
Problem: The name of this user is not daniel (this is the administrator's user name)

**screenshot-admin**

![screenshot-admin](https://user-images.githubusercontent.com/35115643/204997475-b6e9e705-c2a2-44be-9d09-d7e44d780c7c.png)

This is the screenshot for an admin user. 
Problem: The title Smart albums is showing. The actual albums are not visible, but the title uses much needed space. Also, I don't think the block title Albums is necessary because there is already a main title at the top named **Albums**.

**Comment by ildyria** [comment]
- Does the user has any albums ?  Because this does not seem to be the case. 
- Can you try on the current master branch too ? Because there have a been a significant refactoring of the front-end layout.

In the end, I am starting to think there should be a setting to enable/disable smart-albums completely. :')

**Comment by sigulete** [comment]
The user doesn't have albums of her own, the albums in her screen are shared by the admin-user. Ok, maybe that is the reason why the admin-user's username is showing.

I have downloaded the latest version using git, I'm using master (4441064).

Yes, I agree, it would be easier and cleaner to have an option to enable/disable smart-albums.

**Comment by qwerty287** [comment]
Looks like there was a change in some query system: change your CSS to:
```css
[data-id="unsorted"] { display:none; }
[data-id="public"] { display:none; }
[data-id="starred"] { display:none; }
[data-id="recent"] { display:none; }
div#lychee_view_content > div.divider:first-child { display:none; }
div#lychee_view_content > div.divider:nth-child(6) {
    margin-top: 10px;
    border-top: 0;
    box-shadow: none;
}
```

I'll update the website.
