### ISSUE TITLE
Download button is visible and does not support download rights yet. (backend is fine).

### ISSUE THREAD

**Issue by WolfRevo** [LycheeOrg/Lychee#1720]
### Detailed description of the problem [REQUIRED]
Hi,

yesterday I installed lychee 4.7.0 using the official docker container, so this is basically my docker-compose file:

```
cat <fancy path>/docker-compose.yml
#-------------------------------------------
#  Docker Compose
# @RobLandry
# Repo : https://github.com/LycheeOrg/Lychee-Laravel-Docker
#-------------------------------------------

version: '3'

services:
  lychee_db:
    container_name: lychee_db
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=<substituted fancy PW>
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=<substituted fancy second PW>
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - lychee
    dns:
      - <fancy DNS IP>
#    security_opt: ## commented out to proof it's not the cause
#      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 4G
        reservations:
          memory: 500M
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"

  lychee:
    image: lycheeorg/lychee:dev
    container_name: lychee
    ports:
      - 90:80
    volumes:
      - ./lychee/conf:/conf
      - ./lychee/uploads:/uploads
      - ./lychee/sym:/sym
    networks:
      - lychee
      - proxy
    environment:
      - PHP_TZ=Europe/Berlin
      - TIMEZONE=Europe/Berlin
      - DB_CONNECTION=mysql
      - DB_HOST=lychee_db
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=lychee
      - DB_PASSWORD=<substituted fancy second PW>
      - STARTUP_DELAY=30
    dns:
      - <fancy DNS IP>
#    security_opt: ## commented out to proof it's not the cause
#      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 2G
        reservations:
          memory: 250M
    restart: unless-stopped
    depends_on:
      - lychee_db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.lychee.entryPoints=https"
      - "traefik.http.routers.lychee.rule=Host(`<fancy private URL>`)"
      - "traefik.http.routers.lychee.tls=true"
      - "traefik.http.routers.lychee.tls.certResolver=http"
      - "traefik.http.routers.lychee.middlewares= default@file"
      - "traefik.http.routers.lychee.service=lychee"
      - "traefik.http.services.lychee.loadBalancer.server.port=80"
      - "traefik.http.services.lychee.loadbalancer.sticky.cookie.httpOnly=true"
      - "traefik.http.services.lychee.loadbalancer.sticky.cookie.secure=true"

networks:
  lychee:
  proxy:
    external: true

volumes:
  mysql:
```

So with that lychee is perfectly fine reachable via my private URL or locally directly connected to the server (http://\<fancy IP\>:90) and working as authenticated user (either admin or standard user) looks also fine.
As my intention is to use this a way to provide access to specific albums to people without them having an account but still don't want to have the pictures fully publicly exposed to the internet I want to achieve this by the following anonymous settings for my test album:
![grafik](https://user-images.githubusercontent.com/38487435/212868945-8cc84d07-ba43-4850-9b53-6c997bb4dadd.png)

Accessing the album without user looks good in the first place:
![grafik](https://user-images.githubusercontent.com/38487435/212869054-567d3452-ef8b-4515-8657-78da28bc4cfc.png)

Downloading the full album works also as intented (I tried the download and it works):
![grafik](https://user-images.githubusercontent.com/38487435/212869146-6388c231-e2bc-4a9b-90b0-9f1949858e9d.png)

Now I want the anon-user also to be able to download only specific pictures in different sizes (as set per user settings above), but selecting a picture does not show the three dots in the right to download a picture:
![grafik](https://user-images.githubusercontent.com/38487435/212869440-295a409d-e0e4-47f3-8d4f-eb28438859b7.png)

Interestingly if I change the anon-settings to a wrong state:
![grafik](https://user-images.githubusercontent.com/38487435/212869597-a5c943cc-4fce-4cc2-ae88-800ccdc9c4eb.png)

the anon-user should not be able to see the three dots or to download the picture, but:
![grafik](https://user-images.githubusercontent.com/38487435/212869699-342809f7-081a-4a25-a7bb-7a8071d1c445.png)

now he sees the three dots and is also able to click on the different sizes:
![grafik](https://user-images.githubusercontent.com/38487435/212871798-997f2aad-33d9-4c50-9192-39b10e3c0ea8.png)

luckily the permissions are still fine:
![grafik](https://user-images.githubusercontent.com/38487435/212869831-cc33696e-481e-4731-8e6f-d0dac362adbf.png)

I checked your demo page and there it seems to be all right. So did I do something wrong in my docker setup or in the configuration?

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
See the detailed description above, it contains my steps.

**Screenshots**
See the screenshots above.

### Output of the diagnostics  [REQUIRED]
```
    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Info: Latest version of PHP is 8.2
    Warning: git (software) is not available.
    Foreign key: albums.parent_id               → albums.id            : RESTRICT
    Foreign key: albums.id                      → base_albums.id       : RESTRICT
    Foreign key: albums.cover_id                → photos.id            : CASCADE
    Foreign key: base_albums.owner_id           → users.id             : RESTRICT
    Foreign key: photos.album_id                → albums.id            : RESTRICT
    Foreign key: photos.owner_id                → users.id             : RESTRICT
    Foreign key: size_variants.photo_id         → photos.id            : RESTRICT
    Foreign key: sym_links.size_variant_id      → size_variants.id     : RESTRICT
    Foreign key: tag_albums.id                  → base_albums.id       : RESTRICT
    Foreign key: user_base_album.base_album_id  → base_albums.id       : CASCADE
    Foreign key: user_base_album.user_id        → users.id             : CASCADE




    System Information
    --------------
    Lychee Version (git):                    master (26d9b75) -- 2 commits behind 1dd61c1 (2 seconds ago)
    DB Version:                              4.7.0
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  Linux
    PHP Version:                             8.1.12
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                Europe/Berlin
    Max uploaded file size:                  100M
    Max post size:                           100M
    Max execution time:                      3600
    MySQL Version:                           10.10.2-MariaDB-1:10.10.2+maria~ubu2204
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1691
    GD Version:                              2.3.3
    Number of foreign key:                   11 found.




    Config Information
    --------------
    version:                                 040700
    check_for_updates:                       0
    sorting_photos_col:                      taken_at
    sorting_photos_order:                    ASC
    sorting_albums_col:                      max_taken_at
    sorting_albums_order:                    ASC
    imagick:                                 1
    skip_duplicates:                         0
    small_max_width:                         0
    small_max_height:                        360
    medium_max_width:                        1920
    medium_max_height:                       1080
    lang:                                    en
    layout:                                  1
    image_overlay_type:                      desc
    default_license:                         none
    compression_quality:                     90
    grants_full_photo_access:                1
    delete_imported:                         0
    mod_frame_enabled:                       1
    mod_frame_refresh:                       30
    thumb_2x:                                1
    small_2x:                                1
    medium_2x:                               1
    landing_page_enable:                     0
    site_owner:                              Wolf Revo
    landing_title:                           Wolf Revo
    landing_subtitle:                        
    sm_facebook_url:                         
    sm_flickr_url:                           
    sm_twitter_url:                          
    sm_instagram_url:                        
    sm_youtube_url:                          
    landing_background:                      dist/cat.webp
    site_title:                              Wolfi's Bilderbude
    footer_show_copyright:                   1
    site_copyright_begin:                    2015
    site_copyright_end:                      2023
    footer_additional_text:                  
    footer_show_social_media:                0
    public_search:                           0
    SL_enable:                               0
    SL_for_admin:                            0
    public_recent:                           0
    recent_age:                              1
    public_starred:                          0
    grants_download:                         0
    photos_wraparound:                       1
    map_display:                             0
    zip64:                                   1
    map_display_public:                      0
    map_provider:                            Wikimedia
    force_32bit_ids:                         0
    map_include_subalbums:                   0
    update_check_every_days:                 3
    has_exiftool:                            1
    share_button_visible:                    0
    import_via_symlink:                      0
    has_ffmpeg:                              1
    location_decoding:                       0
    location_decoding_timeout:               30
    location_show:                           0
    location_show_public:                    0
    rss_enable:                              0
    rss_recent_days:                         7
    rss_max_items:                           100
    prefer_available_xmp_metadata:           0
    editor_enabled:                          1
    lossless_optimization:                   0
    swipe_tolerance_x:                       150
    swipe_tolerance_y:                       250
    local_takestamp_video_formats:           .avi|.mov
    log_max_num_line:                        1000
    unlock_password_photos_with_url_param:   0
    nsfw_visible:                            0
    nsfw_blur:                               0
    nsfw_warning:                            0
    nsfw_warning_admin:                      0
    nsfw_banner_override:                    
    map_display_direction:                   1
    album_subtitle_type:                     oldstyle
    upload_processing_limit:                 4
    public_photos_hidden:                    1
    new_photos_notification:                 0
    legacy_id_redirection:                   1
    zip_deflate_level:                       6
    SA_enabled:                              1
    default_album_protection:                1
    album_decoration:                        layers
    album_decoration_orientation:            row
    allow_username_change:                   1
```

### Browser and system
Windows 10, Firefox, Edge, Chrome (tested with them all)
