### ISSUE TITLE
[BUG] 500 after update from 4.7.0 from 4.7.3

### ISSUE THREAD

**Issue by LotuxPunk** [LycheeOrg/Lychee#1805]
### Detailed description of the problem [REQUIRED]
500 after update from 4.7.0 from 4.7.3

Reported the error to linuxserver, but they said the error should be upstream: https://github.com/linuxserver/docker-lychee/issues/62

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
Update Lychee from 4.7.0 to 4.7.3

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

![image](https://user-images.githubusercontent.com/16562647/233781359-5abac07f-5765-4805-b73e-e39169520d50.png)

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

```bash
root@8eabd9295a3c:/app/www# php artisan lychee:diagnostics

In PackageManifest.php line 178:

  The /app/www/bootstrap/cache directory must be present and writable.
```

### Docker container logs

```
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
Connection to mariadb 3306 port [tcp/mysql] succeeded!

In PackageManifest.php line 178:
                                                                        
  The /app/www/bootstrap/cache directory must be present and writable.  
                                                                        

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

### Browser and system

OS: Ubuntu 22.04
Docker: https://hub.docker.com/layers/linuxserver/lychee/4.7.3/images/sha256-c74fa667f77bbb57c267ab1604204e2135649ff0273b8811a9b1e7ebb63ae681?context=explore

Docker compose:

```yaml
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: lychee_mariadb
    restart: always
    volumes:
      - ./kameo/lychee/mysql:/config
    environment:
      - MYSQL_ROOT_PASSWORD=****
      - MYSQL_DATABASE=****
      - MYSQL_USER=****
      - MYSQL_PASSWORD=****
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Brussels
    ports:
      - 3306:3306
  lychee:
    image: lscr.io/linuxserver/lychee:latest
    container_name: lychee
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ./kameo/lychee/config:/config
      - ./kameo/lychee/pictures:/pictures
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=***
      - DB_PASSWORD=***
      - DB_DATABASE=***
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Brussels
    ports:
      - 86:80
      - 87:443
 ``` 
      
 After some investigation found out that:
```bash
root@8eabd9295a3c:/app/www/bootstrap# ls -lha
total 28K
drwxr-xr-x 1 abc users 4.0K Apr 19 08:34 .
drwxr-xr-x 1 abc users 4.0K Apr 21 15:54 ..
-rw-r--r-- 1 abc users 3.7K Apr 19 08:34 PanicAttack.php
-rw-r--r-- 1 abc users 2.4K Apr 19 08:34 app.php
lrwxrwxrwx 1 abc users   26 Apr 19 08:34 cache -> ../storage/bootstrap/cache
-rw-r--r-- 1 abc users 1.4K Apr 19 08:34 initialize.php
```

cache of bootstrap is a symlink pointing to storage

And indeed, there's nothing inside storage that correspond to `bootstrap/cache`

```bash
root@8eabd9295a3c:/app/www/storage# ls -lha
total 24K
drwxrwxr-x  6 abc users 4.0K Aug  5  2022 .
drwxr-xr-x 10 abc users 4.0K Feb 25 21:06 ..
drwxrwxr-x  3 abc users 4.0K Aug  5  2022 app
drwxrwxr-x  2 abc users 4.0K Aug  5  2022 debugbar
drwxrwxr-x  6 abc users 4.0K Aug  5  2022 framework
drwxrwxr-x  2 abc users 4.0K Aug 21  2022 logs
```
