### ISSUE TITLE
[Enhancement] Support Environment-Variable Configured Administrator Account Credentials

### ISSUE THREAD

**Issue by engineerjoe440** [LycheeOrg/Lychee#1858]
Hi there! LOVE this project! Nice and simple little application that is super helpful and provides a great API for additional development.

### Request
* Add ability to configure the administrator user account with an environment variable to support CI-based deployment with a system like Jenkins.

### Background
I'm working with youth, developing an [open-source photo upload application](https://gitlab.stanleysolutionsnw.com/idaho4h/4HPhotoUploader) for youth conferences and events organized by 4-H. The app serves as a simple frontend to support automatic uploads to Lychee into albums as specified by the uploader.

The workflow basically constitutes a youth-delegate taking a picture, navigating to the photo upload site, and selecting whether they're participating in a "district competition," "scavenger hunt," or just want to upload a general picture. From there, they select the pictures they wish to upload, press submit, and let the app do the rest.

The app uploads those photos to the "correct" album according to the youth's selections. It's a niche application, but it's super useful!

In my development, and work with this system, I'd like to be able to provide a `docker-compose.yml` example that would set up the full application and Lychee backend with a valid admin-account to manage the interactions (ideally, a non-admin user, too, but that's a different story). Additionally, this would allow me to put together a more cohesive automated test framework.

Is it possible to configure the user account from a set of environment variables, or some other "scriptable" interface?

**Comment by mingan666** [comment]
Not yet tested this myself, but I was thinking to create a sql export to achieve similar.
Basically start a minimum lychee service with a docker-compose, create the user accounts needed and then create a sql dump.
Thereafter update the docker-compose with necessary env variable to import the sql during startup.

 ```
  db:
    image: mariadb:10.9
    networks:
      - net
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
      - ./test-lychee.sql:/docker-entrypoint-initdb.d/test-lychee.sql         =>  link the dump file into the container
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=xxx
      - MYSQL_PASSWORD=xxx
 ```
