### ISSUE TITLE
Migration not working to create FK on oauth table

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee#2289]
@DLYSY reported the following. During manual migration.

```
2024_01_13_124937_create_oauth_credentials_table ................ 140ms FAIL In Connection.php line 822:
 SQLSTATE[HY000]: General error: 3780 Referencing column 'user_id' and refer
 enced column 'id' in foreign key constraint 'oauth_credentials_user_id_foreign'
 are incompatible. (Connection: mysql, SQL: alter table `oauth_credentials` add
constraint `oauth_credentials_user_id_foreign` foreign key (`user_id`) references
`users` (`id`) on delete cascade on update cascade)

In Connection.php line 580:
SQLSTATE[HY000]: General error: 3780 Referencing column 'user_id' and refer
enced column 'id' in foreign key constraint 'oauth_credentials_user_id_foreign'
are incompatible.
```

- [x] tested on SQLITE 3.44.2  **Not reproducible**
- [x] tested on my own server MariaDB 10.11.6-MariaDB-1:10.11.6+maria~ubu2204 **Not reproducible**
- [x] Test on MySql server 8.3. **Not reproducible** (did creation at 5.0.2 then bump the docker file to 5.1.2)

**Comment by ildyria** [comment]
@DLYSY Would it be possible for you to provide me with a dump of your DB? because I really can't reproduce that one.
I tried all the DB versions I could think off (sqlite, mariadb, mysql) and I can get that error to show up.

**Comment by DLYSY** [comment]
[lychee.zip](https://github.com/LycheeOrg/Lychee/files/14224491/lychee.zip)

**Comment by ildyria** [comment]
> [lychee.zip](https://github.com/LycheeOrg/Lychee/files/14224491/lychee.zip)

Thanks!

So I had a look and compared to a fresh 5.0.3 **Mysql** dump.
I used the following docker-compose file:
```yaml
#-------------------------------------------
#  Docker Compose
# @RobLandry
# Repo : https://github.com/LycheeOrg/Lychee-Docker
#-------------------------------------------

version: '3'

services:
  lychee_db_mysql:
    container_name: lychee_db_mysql
    image: mysql:8.3
    environment:
      - MYSQL_ROOT_PASSWORD=root_pw
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=password
    expose: 
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - lychee_mysql_network
    restart: unless-stopped

  lychee:
    image: lycheeorg/lychee:v5.0.3
    container_name: lychee_mysql
    ports:
      - 90:80
    volumes:
      - ./lychee/conf:/conf
      - ./lychee/uploads:/uploads
      - ./lychee/sym:/sym
      - ./lychee/logs:/logs
    networks:
      - lychee_mysql_network
    environment:
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      - DB_CONNECTION=mysql
      - DB_HOST=lychee_db_mysql
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=lychee
      - DB_PASSWORD=password
      - STARTUP_DELAY=30
    restart: unless-stopped
    depends_on:
      - lychee_db_mysql

networks:
  lychee_mysql_network:

volumes:
  mysql:
```
As you can see, this is pulling image **5.0.3.**, which I gathered you were using from your db dump:
```
(1, 'version', '050003', 'Admin', 'int', 0, 'Current version of Lychee'),
```

Now after `docker compose up`, I pulled the data from the DB:
```
docker exec -i lychee_db_mysql /usr/bin/mysqldump -u root --password=root_pw lychee > lychee-mysql.sql
```

Now comparing the two:
Your user table query is as follows:
```sql
--
-- 表的结构 `users`
--

CREATE TABLE `users` (
  `id` bigint DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `username` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `password` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `may_administrate` tinyint(1) DEFAULT NULL,
  `token` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `may_upload` tinyint(1) DEFAULT NULL,
  `may_edit_own_settings` tinyint(1) DEFAULT NULL,
  `remember_token` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
```
Mine is:
```sql
CREATE TABLE `users` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `username` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `may_administrate` tinyint(1) NOT NULL DEFAULT '0',
  `token` char(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `may_upload` tinyint(1) NOT NULL DEFAULT '0',
  `may_edit_own_settings` tinyint(1) NOT NULL DEFAULT '0',
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_username_unique` (`username`),
  UNIQUE KEY `users_email_unique` (`email`),
  UNIQUE KEY `users_token_unique` (`token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

```

I would be enclined to believe that this difference in `id` type is source of our conflict.
