### ISSUE TITLE
[Enhancement] Font size on Diagnostics and Logs

### ISSUE THREAD

**Issue by ericgaspar** [LycheeOrg/Lychee#797]
Increasing the font size in ~~admin~~ *the diagnostics and logs* panels will be easy on the eyes (especially for older user). For the moment it's tiny beyond reason

**Comment by d7415** [comment]
The font in the admin panels looks about the same as the rest of the site. Presumably if it's too small there it's too small everywhere - It follows the browser's zoom settings, so is best adjusted there.

**Comment by ericgaspar** [comment]
> The font in the admin panels looks about the same as the rest of the site. Presumably if it's too small there it's too small everywhere - It follows the browser's zoom settings, so is best adjusted there.

well not exactly 

as you can see the left panel is ok and the diagnostics are tiny...

![Capture d’écran 6](https://user-images.githubusercontent.com/46165813/99875349-23a31300-2bef-11eb-8bdd-f1669834db1a.png)

Also, I don't think zooming the entire app is a solution because it zooms in on things that don't need to be bigger: images, icons ...

**Comment by ericgaspar** [comment]
and also I don't know why this issue is beeing closed so quicly...

**Comment by d7415** [comment]
Ok, the Diagnostics page is actually smaller. You just needed to state the problem more clearly.

**Comment by d7415** [comment]
> and also I don't know why this issue is beeing closed so quicly...

Because your original stated issue wasn't one.

**Comment by ericgaspar** [comment]
When I am refering to *admin panels* I am refering  to : *Settings*, *Users*, *Sharing*, *Show Logs* and *Diagnostics* pages to be precise.

**Comment by d7415** [comment]
> When I am refering to _admin panels_ I am refering to : _Settings_, _Users_, _Sharing_, _Show Logs_ and _Diagnostics_ pages to be precise.

Settings, Users and Sharing use the same font size as the rest of the UI, as previously stated.

**Comment by ildyria** [comment]
You can use `user.css` to fix it in (Settings -> personalize your CSS).

**Comment by ericgaspar** [comment]
@ildyria Thanks for the advice.
Do you have a clue on what css parameter should I change to make the diagnostics font size bigger?

BTW Lychee is now part of the YunoHost catalog: https://github.com/YunoHost-Apps/lychee_ynh

**Comment by ildyria** [comment]
```css
.settings_view p, .settings_view a, .settings_view input,
.sharing_view p, .sharing_view a, .sharing_view input,  .sharing_view option,
.users_view p, .users_view a, .users_view input, .users_view option,
.logs_diagnostics_view pre {
    font-size: 24pt;
    line-height: 24pt;
}
```

Note that 24pt might be a bit too big. Feel free to adjust the value to your tastes.
