### ISSUE TITLE
"Class 'Http\Adapter\Guzzle6\Client' not found" when trying to convert GPS data

### ISSUE THREAD

**Issue by pichouk** [LycheeOrg/Lychee#998]
Hi,

I just setup a Lychee server using Docker. Here is an extract of my Docker Compose file : 

```
version: "3"
services:
  lychee:
    image: lycheeorg/lychee:v4.3.0
    container_name: lychee
    environment:
      PUID: 1723
      PGID: 1723
      PHP_TZ: Europe/Paris
      DB_CONNECTION: pgsql
      DB_HOST: lychee-db
      DB_PORT: 5432
      DB_DATABASE: lychee
      DB_USERNAME: lychee
      DB_PASSWORD: mysuperpassword
    volumes:
      - /docker/volumes/lychee/conf:/conf
      - /docker/volumes/lychee/uploads:/uploads
      - /docker/volumes/lychee/sym:/sym
```

I tried to import several files from the Web UI and I had an error during the import, without any specific log. long story short, I figured out that it was because of the feature "convert GPS data to location" that was enable.

Inside my Docker container, when I run `php artisan lychee:decode_GPS_locations` I was this single message : 

```
In Geodecoder.php line 35:                                             
  Class 'Http\Adapter\Guzzle6\Client' not found 
```

My container seems to have Internet access and I can can `curl` several websites from the container. Is that possible that there s a missing PHP library or something ?
